# Generated by Django 4.0.4 on 2022-05-31 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplicatie_projects', '0002_alter_projects_responsible_engineer'),
        ('aplicatie_items', '0004_alter_items_price_alter_items_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_items.items')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_projects.projects')),
            ],
        ),
    ]
