# Generated by Django 4.0.4 on 2022-05-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Fittings', 'fittings'), ('Adaptors', 'adaptors'), ('Ball Valves', 'b_valves'), ('Check Valves', 'c_valves'), ('Relief Valves', 'r_valves'), ('Pressure Indicators', 'p_indicators'), ('Temperature Indicators', 't_indicators')], max_length=100)),
                ('item_no', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('auto_po', models.BooleanField(default=1)),
                ('auto_po_qty', models.CharField(choices=[('n/a', 'n_a'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20')], max_length=100)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
    ]
