# Generated by Django 4.0.4 on 2022-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_items', '0002_alter_items_auto_po_qty_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='auto_po_qty',
            field=models.CharField(choices=[('n/a', 'n_a'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20')], max_length=100),
        ),
        migrations.AlterField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('Fittings', 'fittings'), ('Adaptors', 'adaptors'), ('Ball Valves', 'b_valves'), ('Check Valves', 'c_valves'), ('Relief Valves', 'r_valves'), ('Pressure Indicators', 'p_indicators'), ('Temperature Indicators', 't_indicators')], max_length=100),
        ),
    ]
