# Generated by Django 4.0.4 on 2022-05-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_items', '0003_alter_items_auto_po_qty_alter_items_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='items',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
