# Generated by Django 4.0.4 on 2022-05-30 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aplicatie_items', '0003_alter_items_auto_po_qty_alter_items_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=1)),
                ('responsible_engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicatie_items.items')),
            ],
        ),
    ]
